# Site settings
author: Daniel Campo
title: software engineering??
header-img: img/home-bg.png
email: campo_daniel94@yahoo.com
copyright_name: Daniel Campo
description: > # this means to ignore newlines until "baseurl:"
  why i chose web dev
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  danielcampo1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
